In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r'C:\Users\Avishkar\Downloads\dataset_Facebook.csv',sep = ';')
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [8]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [9]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [10]:
df.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [11]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [13]:
sub1 = df[['Type','like','share']]
sub1

       Type    like  share
0     Photo    79.0   17.0
1    Status   130.0   29.0
2     Photo    66.0   14.0
3     Photo  1572.0  147.0
4     Photo   325.0   49.0
..      ...     ...    ...
495   Photo    53.0   26.0
496   Photo    53.0   22.0
497   Photo    93.0   18.0
498   Photo    91.0   38.0
499   Photo    91.0   28.0

[500 rows x 3 columns]

In [18]:
#row subset
sub_row = df[df['Type'] == 'Photo']
sub_row.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [26]:
#subsets using loc
sub_loc = df.loc[1:10, ['Type','like']]
sub_loc

      Type    like
1   Status   130.0
2    Photo    66.0
3    Photo  1572.0
4    Photo   325.0
5   Status   152.0
6    Photo   249.0
7    Photo   325.0
8   Status   161.0
9    Photo   113.0
10  Status   233.0

In [29]:
#merging two subsets
merged_data = pd.merge(sub_loc,sub1, on= "like")
merged_data

    Type_x    like  Type_y  share
0   Status   130.0  Status   29.0
1   Status   130.0    Link   31.0
2    Photo    66.0   Photo   14.0
3    Photo    66.0   Photo   12.0
4    Photo    66.0   Photo   13.0
5    Photo    66.0   Photo    9.0
6    Photo    66.0   Photo   13.0
7    Photo  1572.0   Photo  147.0
8    Photo   325.0   Photo   49.0
9    Photo   325.0   Photo   14.0
10  Status   152.0  Status   33.0
11  Status   152.0   Photo   41.0
12  Status   152.0   Photo   11.0
13   Photo   249.0   Photo   27.0
14   Photo   325.0   Photo   49.0
15   Photo   325.0   Photo   14.0
16  Status   161.0  Status   31.0
17  Status   161.0   Photo   25.0
18   Photo   113.0   Photo   26.0
19   Photo   113.0   Photo   19.0
20   Photo   113.0   Photo   17.0
21   Photo   113.0   Photo   20.0
22  Status   233.0  Status   19.0

In [34]:
#sorting of data
sort_df = merged_data.sort_values(by = ['share','like'], ascending = [True,False])
sort_df

    Type_x    like  Type_y  share
5    Photo    66.0   Photo    9.0
12  Status   152.0   Photo   11.0
3    Photo    66.0   Photo   12.0
4    Photo    66.0   Photo   13.0
6    Photo    66.0   Photo   13.0
9    Photo   325.0   Photo   14.0
15   Photo   325.0   Photo   14.0
2    Photo    66.0   Photo   14.0
20   Photo   113.0   Photo   17.0
22  Status   233.0  Status   19.0
19   Photo   113.0   Photo   19.0
21   Photo   113.0   Photo   20.0
17  Status   161.0   Photo   25.0
18   Photo   113.0   Photo   26.0
13   Photo   249.0   Photo   27.0
0   Status   130.0  Status   29.0
16  Status   161.0  Status   31.0
1   Status   130.0    Link   31.0
10  Status   152.0  Status   33.0
11  Status   152.0   Photo   41.0
8    Photo   325.0   Photo   49.0
14   Photo   325.0   Photo   49.0
7    Photo  1572.0   Photo  147.0

In [35]:
#transposing data
trans_data = merged_data.T
trans_data

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
Type_x,Status,Status,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,...,Photo,Photo,Photo,Status,Status,Photo,Photo,Photo,Photo,Status
like,130.0,130.0,66.0,66.0,66.0,66.0,66.0,1572.0,325.0,325.0,...,249.0,325.0,325.0,161.0,161.0,113.0,113.0,113.0,113.0,233.0
Type_y,Status,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,...,Photo,Photo,Photo,Status,Photo,Photo,Photo,Photo,Photo,Status
share,29.0,31.0,14.0,12.0,13.0,9.0,13.0,147.0,49.0,14.0,...,27.0,49.0,14.0,31.0,25.0,26.0,19.0,17.0,20.0,19.0

In [36]:
df.shape

(500, 19)

In [37]:
melted_df = pd.melt(df, id_vars = ['Type'], value_vars = ['like','share'])
melted_df

       Type variable   value
0     Photo     like    79.0
1    Status     like   130.0
2     Photo     like    66.0
3     Photo     like  1572.0
4     Photo     like   325.0
..      ...      ...     ...
995   Photo    share    26.0
996   Photo    share    22.0
997   Photo    share    18.0
998   Photo    share    38.0
999   Photo    share    28.0

[1000 rows x 3 columns]

In [38]:
melted_df1 = pd.melt(df , id_vars = ['like'], value_vars = ['share', 'Type'])
melted_df1

       like variable  value
0      79.0    share   17.0
1     130.0    share   29.0
2      66.0    share   14.0
3    1572.0    share  147.0
4     325.0    share   49.0
..      ...      ...    ...
995    53.0     Type  Photo
996    53.0     Type  Photo
997    93.0     Type  Photo
998    91.0     Type  Photo
999    91.0     Type  Photo

[1000 rows x 3 columns]

In [47]:
pivot_df = df.pivot_table(values = "like", index = "Type", aggfunc = "count")
pivot_df

        like
Type
Link      22
Photo    425
Status    45
Video      7

In [46]:
#pivot table

pivot_df = df.pivot_table(values = "like", index = "Type", columns = "Category", aggfunc = "count")
pivot_df

Category      1     2      3
Type
Link       20.0   1.0    1.0
Photo     184.0  91.0  150.0
Status      3.0  38.0    4.0
Video       7.0   NaN    NaN